"""convert_template_ids_to_integer

Revision ID: e905398f7c54
Revises: d55918878800
Create Date: 2025-07-20 15:54:01.098653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e905398f7c54'
down_revision = 'd55918878800'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update the data in templates table
    op.execute("UPDATE templates SET template_id = CASE "
               "WHEN template_id = 'professional' THEN 1 "
               "WHEN template_id = 'modern' THEN 2 "
               "WHEN template_id = 'creative' THEN 3 "
               "WHEN template_id = 'minimalist' THEN 4 "
               "WHEN template_id = 'executive' THEN 5 "
               "WHEN template_id = '1' THEN 1 "
               "WHEN template_id = '2' THEN 2 "
               "WHEN template_id = '3' THEN 3 "
               "WHEN template_id = '4' THEN 4 "
               "WHEN template_id = '5' THEN 5 "
               "ELSE 1 END")
    
    # Update the data in resumes table
    op.execute("UPDATE resumes SET template_id = CASE "
               "WHEN template_id = 'professional' THEN 1 "
               "WHEN template_id = 'modern' THEN 2 "
               "WHEN template_id = 'creative' THEN 3 "
               "WHEN template_id = 'minimalist' THEN 4 "
               "WHEN template_id = 'executive' THEN 5 "
               "WHEN template_id = '1' THEN 1 "
               "WHEN template_id = '2' THEN 2 "
               "WHEN template_id = '3' THEN 3 "
               "WHEN template_id = '4' THEN 4 "
               "WHEN template_id = '5' THEN 5 "
               "ELSE 1 END")
    
    # Now alter the column types
    op.alter_column('resumes', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="template_id::integer")
    op.alter_column('templates', 'template_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="template_id::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'template_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('resumes', 'template_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ### 