"""add_resume_id_to_user_sessions

Revision ID: ed872adc4e1f
Revises: 327a267b6293
Create Date: 2025-07-20 21:20:53.375997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed872adc4e1f'
down_revision = '327a267b6293'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'schema_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('user_sessions', sa.Column('resume_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_sessions', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_column('user_sessions', 'resume_id')
    op.alter_column('resumes', 'schema_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ### 